import { test, before, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { Pool } from 'pg';
import { PostgresProofUnitOfWork } from '../../src/infrastructure/postgres/proof-unit-of-work.ts';
import { requestReservation, ReservationConflict } from '../../src/application/request-reservation.ts';

// Fixed local disposable target. Never read a production DATABASE_URL here.
const config = { host:'127.0.0.1',port:55439,user:'pm_test',password:'pm_local_test_only',connectionTimeoutMillis:3000 };
const name = `pm_proof_${randomUUID().replaceAll('-','')}`;
const admin = new Pool({...config,database:'pm_foundation'});
const pool = new Pool({...config,database:name,max:8});
const uow = new PostgresProofUnitOfWork(pool);
const org = randomUUID(), owner = randomUUID(), partner = randomUUID(), org2 = randomUUID();
const driver = randomUUID(), driver2 = randomUUID(), car = randomUUID(), car2 = randomUUID(), foreignCar = randomUUID();
const actor = {organizationId:org,userId:owner};
const start = new Date(Date.now()+86400000).toISOString();
const end = new Date(Date.parse(start)+3600000).toISOString();
const request = (changes={}) => ({ idempotencyKey:randomUUID(),driverId:driver,vehicleId:car,startsAt:start,endsAt:end,quote:{totalCents:101,depositCents:25,balanceCents:76,tariffVersion:1},...changes });
const reserve = (changes={}) => requestReservation(uow,actor,request(changes),()=>0);
before(async () => {
  assert.match(name,/^pm_proof_[a-f0-9]{32}$/);
  await admin.query(`create database ${name}`);
  await pool.query(await readFile(new URL('../../db/proofs/scheduling.sql',import.meta.url),'utf8'));
  await pool.query('insert into pm_proof.organizations values($1),($2)',[org,org2]);
  await pool.query("insert into pm_proof.memberships values($1,$2,'owner',true),($1,$3,'driver',true)",[org,owner,partner]);
  await pool.query('insert into pm_proof.settings values($1,1,60,15)',[org]);
  for(const [id,kind,tenant] of [[driver,'driver',org],[driver2,'driver',org],[car,'vehicle',org],[car2,'vehicle',org],[foreignCar,'vehicle',org2]]) await pool.query('insert into pm_proof.resources(organization_id,id,kind) values($1,$2,$3)',[tenant,id,kind]);
});
beforeEach(async()=>{
  await pool.query('truncate pm_proof.commands,pm_proof.outbox,pm_proof.allocations,pm_proof.bookings');
  await pool.query('update pm_proof.settings set version=1,minimum_gap=60,tolerance=15');
});
after(async()=>{
  await pool.end();
  // Only the database generated by this test run is removed; no volume or workspace deletion.
  assert.match(name,/^pm_proof_[a-f0-9]{32}$/);
  await admin.query(`drop database if exists ${name}`);
  await admin.end();
});

test('same driver: simultaneous requests produce one booking, two allocations and one event',async()=>{
  const results=await Promise.allSettled([reserve(),reserve({vehicleId:car2})]);
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  const rejected=results.find(r=>r.status==='rejected');
  assert.ok(rejected?.status==='rejected' && rejected.reason instanceof ReservationConflict);
  const {rows}=await pool.query('select (select count(*) from pm_proof.bookings)::int b,(select count(*) from pm_proof.allocations)::int a,(select count(*) from pm_proof.outbox)::int e');
  assert.deepEqual(rows[0],{b:1,a:2,e:1});
});
test('same car and different drivers still collide; independent resources succeed',async()=>{
  const results=await Promise.allSettled([reserve(),reserve({driverId:driver2})]);
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  await pool.query('truncate pm_proof.commands,pm_proof.outbox,pm_proof.allocations,pm_proof.bookings');
  const both=await Promise.all([reserve(),reserve({driverId:driver2,vehicleId:car2})]);
  assert.notEqual(both[0].id,both[1].id);
});
test('transaction actually waits for the resource lock held by another connection',async()=>{
  const blocker=await pool.connect();
  await blocker.query('begin');
  await blocker.query('select id from pm_proof.resources where organization_id=$1 and id=$2 for update',[org,driver]);
  const pending=reserve();
  try {
    let waiting=false;
    for(let i=0;i<100&&!waiting;i++) {
      const {rows}=await admin.query("select count(*)::int n from pg_stat_activity where datname=$1 and wait_event_type='Lock'",[name]);
      waiting=rows[0].n>0;
      if(!waiting)await new Promise(resolve=>setTimeout(resolve,10));
    }
    assert.ok(waiting,'a real PostgreSQL lock wait must be observed');
  } finally { await blocker.query('rollback');blocker.release(); }
  await pending;
});
test('same idempotency key replays one receipt; changed payload is rejected',async()=>{
  const input=request();
  const a=()=>requestReservation(uow,actor,input,()=>0);
  const [first,second]=await Promise.all([a(),a()]);
  assert.deepEqual(first,second);
  await assert.rejects(requestReservation(uow,actor,{...input,vehicleId:car2},()=>0),/Idempotency/);
  assert.equal((await pool.query('select count(*)::int n from pm_proof.bookings')).rows[0].n,1);
});
test('late outbox failure rolls back booking, allocations and command',async()=>{
  await pool.query("alter table pm_proof.outbox add constraint fail_test check(event_type<>'booking.requested')");
  try { await assert.rejects(reserve(),/fail_test/); }
  finally { await pool.query('alter table pm_proof.outbox drop constraint fail_test'); }
  for(const table of ['bookings','allocations','commands','outbox']) assert.equal((await pool.query(`select count(*)::int n from pm_proof.${table}`)).rows[0].n,0);
  await reserve(); // pool and locks remain usable after rollback
});
test('expired holds release availability without deleting historical records',async()=>{
  const first=await reserve();
  await pool.query("update pm_proof.bookings set expires_at=clock_timestamp()-interval '1 second' where id=$1",[first.id]);
  const second=await reserve();
  assert.notEqual(first.id,second.id);
  assert.equal((await pool.query('select count(*)::int n from pm_proof.bookings')).rows[0].n,2);
});
test('database neighbors preserve 60-minute boundary, longer relocation and fail-closed routing',async()=>{
  await reserve();
  const later=(gap:number)=>request({startsAt:new Date(Date.parse(end)+gap*60000).toISOString(),endsAt:new Date(Date.parse(end)+(gap+60)*60000).toISOString()});
  await assert.rejects(requestReservation(uow,actor,later(59),()=>0),ReservationConflict);
  await assert.rejects(requestReservation(uow,actor,later(60),()=>90),ReservationConflict);
  await assert.rejects(requestReservation(uow,actor,later(105),()=>undefined),ReservationConflict);
  await requestReservation(uow,actor,later(105),()=>90);
});
test('quote and policy snapshots remain unchanged after settings revision',async()=>{
  const first=await reserve();
  await pool.query('update pm_proof.settings set version=2,minimum_gap=120');
  const {rows}=await pool.query('select quote_snapshot,policy_snapshot from pm_proof.bookings where id=$1',[first.id]);
  assert.equal(rows[0].quote_snapshot.depositCents,25);
  assert.deepEqual(rows[0].policy_snapshot,{version:1,minimumGapMinutes:60,delayAllowanceMinutes:15});
});
test('partner, unknown actor, cross-tenant and mismatched resource types are rejected',async()=>{
  await assert.rejects(requestReservation(uow,{organizationId:org,userId:partner},request(),()=>0),/Forbidden/);
  await assert.rejects(requestReservation(uow,{organizationId:org,userId:randomUUID()},request(),()=>0),/Forbidden/);
  await assert.rejects(reserve({vehicleId:foreignCar}),/Unavailable/);
  await assert.rejects(reserve({vehicleId:driver2}),/Unavailable/);
  assert.equal((await pool.query('select count(*)::int n from pm_proof.bookings')).rows[0].n,0);
});
test('private proof schema denies an unprivileged database role and enables RLS on every table',async()=>{
  const db=await pool.connect();
  try { await db.query('set role pg_signal_backend');await assert.rejects(db.query('select * from pm_proof.bookings'),/permission denied/); }
  finally {await db.query('reset role');db.release();}
  const {rows}=await pool.query("select count(*)::int n from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='pm_proof' and c.relkind='r' and not c.relrowsecurity");
  assert.equal(rows[0].n,0);
});
test('invalid amounts and intervals are rejected before persistence',async()=>{
  await assert.rejects(reserve({quote:{totalCents:101,depositCents:26,balanceCents:75,tariffVersion:1}}));
  await assert.rejects(reserve({endsAt:start}));
  assert.equal((await pool.query('select count(*)::int n from pm_proof.commands')).rows[0].n,0);
});
