import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('artifacts/checkup', { recursive:true });
const browser = await chromium.launch({channel:'msedge'});
const context = await browser.newContext({viewport:{width:390,height:844},geolocation:{latitude:41.1579,longitude:-8.6291},permissions:['geolocation']});
const page = await context.newPage();
const evidence = {};
await page.goto('http://127.0.0.1:5173/?demo=1#/customer/discover');
await page.evaluate(()=>localStorage.setItem('pm.demo.tours',JSON.stringify([{id:'audit-tour',namePt:'Tour auditoria',nameEn:'Audit tour',descriptionPt:'Teste de preço',descriptionEn:'Price test',durationDays:2,baseCents:34500,extraPassengerCents:5000,minimumNoticeHours:48,active:true,area:'Sintra',photoPath:'/lisbon-sintra-tour.webp'}])));
await page.reload();
await page.getByRole('button',{name:'Abrir tour Tour auditoria',exact:true}).click();
await page.getByRole('button',{name:'Ver rota e preço',exact:true}).click();
evidence.tourPrice = {catalogueCents:34500,quote:await page.locator('.pm-client-route-quote-head').innerText()};
await page.getByRole('button',{name:'Usar localização atual',exact:true}).click();
await page.waitForTimeout(300);
evidence.location = {grantedLocation:'Porto (41.1579, -8.6291)',field:await page.getByLabel('Local de partida',{exact:true}).inputValue(),map:await page.locator('.pm-route-map').getAttribute('aria-label'),text:await page.locator('.pm-route-points').innerText()};
await page.goto('http://127.0.0.1:5173/?demo=1#/customer/booking');
await page.getByRole('button',{name:'Continuar',exact:true}).click();
await page.getByRole('button',{name:'Continuar',exact:true}).click();
await page.getByLabel('Nome completo',{exact:true}).fill('   ');
await page.getByLabel('Email',{exact:true}).fill('audit@example.invalid');
await page.getByLabel('Telefone',{exact:true}).fill('abc');
await page.getByLabel('NIF',{exact:true}).fill('000000000');
await page.getByRole('button',{name:'Continuar',exact:true}).click();
evidence.invalidDetails = {blankName:true,phone:'abc',nif:'000000000',reviewVisible:await page.getByRole('heading',{name:'Rever pedido',exact:true}).isVisible()};
await page.goto('http://127.0.0.1:5173/?demo=1#/owner/home');
const before=await page.locator('main').innerText();
await page.getByRole('button',{name:'Perfil',exact:true}).click();
evidence.profileButton={unchanged:before===await page.locator('main').innerText(),url:page.url()};
await page.getByRole('button',{name:'Mais opções',exact:true}).click();
evidence.moreButton={unchanged:before===await page.locator('main').innerText(),url:page.url()};
await writeFile('artifacts/checkup/probes.json',JSON.stringify(evidence,null,2));
console.log(JSON.stringify(evidence,null,2));
await browser.close();
