import { useEffect, useState } from 'react';
import { Plus, Save, UserRound, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { isCustomerPublishable } from '../../contracts/customer';
import { Button } from '../../ui/components/Button';
import { Row, Section } from '../../ui/components/Primitives';
import { readDemoCustomerRequests, subscribeToDemoCustomerRequests, type DemoCustomerRequest } from '../demo-request-store';

type Customer={id:string;fullName:string;email:string;phone:string;nif:string;notes:string;requestId?:string};
const initial:Customer[]=[{id:'c1',fullName:'Ana Exemplo',email:'ana@example.invalid',phone:'+351 910 000 010',nif:'123456789',notes:'Prefere recolha no hotel.'},{id:'c2',fullName:'Daniel Exemplo',email:'daniel@example.invalid',phone:'+351 910 000 011',nif:'234567890',notes:''},{id:'c3',fullName:'Emma Example',email:'emma@example.invalid',phone:'+351 910 000 012',nif:'345678901',notes:'English preferred.'}];
const customerFromRequest=(request:DemoCustomerRequest):Customer=>({id:`request-${request.id}`,requestId:request.id,fullName:request.name,email:request.email,phone:request.phone,nif:request.nif,notes:`${request.origin} → ${request.destination} · ${request.id}`});
export function CustomerCrmSandbox(){
  const {i18n}=useTranslation();const en=i18n.language==='en';const say=(pt:string,english:string)=>en?english:pt;const [customers,setCustomers]=useState<Customer[]>(()=>[...initial,...readDemoCustomerRequests().map(customerFromRequest)]);const [search,setSearch]=useState('');const [showForm,setShowForm]=useState(false);const [feedback,setFeedback]=useState('');
  useEffect(() => { const refresh = () => setCustomers(current => [...current.filter(customer => !customer.requestId), ...readDemoCustomerRequests().map(customerFromRequest)]); return subscribeToDemoCustomerRequests(refresh); }, []);
  const add=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const row={fullName:String(form.get('name')||''),email:String(form.get('email')||''),phone:String(form.get('phone')||''),nif:String(form.get('nif')||''),notes:String(form.get('notes')||'')};if(!isCustomerPublishable(row)){setFeedback(say('Verifique nome, email, telefone e NIF de 9 dígitos.','Check name, email, phone and the 9-digit tax ID.'));return;}setCustomers(rows=>[...rows,{id:`c${Date.now()}`,...row}]);setShowForm(false);setFeedback(say('Cliente adicionado ao CRM de teste.','Customer added to the test CRM.'));};
  const filtered=customers.filter(row=>Object.values(row).join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  return <><p className="pm-note">{say('CRM de teste · dados fictícios e alterações apenas em memória.','Test CRM · fictional data and memory-only changes.')}</p><div className="pm-actions"><Button onClick={()=>{setShowForm(value=>!value);setFeedback('');}}>{showForm?<><X size={17} aria-hidden="true" />{say('Fechar formulário','Close form')}</>:<><Plus size={17} aria-hidden="true" />{say('Novo cliente','New customer')}</>}</Button></div>{showForm&&<form className="pm-card pm-form" aria-label={say('Novo cliente','New customer')} onSubmit={add}><label>{say('Nome completo','Full name')}<input name="name" required maxLength={200}/></label><label>Email<input name="email" type="email" required maxLength={254}/></label><label>{say('Telefone','Phone')}<input name="phone" required minLength={7} maxLength={30}/></label><label>NIF<input name="nif" inputMode="numeric" pattern="[0-9]{9}" required/></label><label>{say('Notas internas','Internal notes')}<textarea name="notes" maxLength={2000}/></label>{feedback&&<p role="alert">{feedback}</p>}<Button type="submit"><Save size={17} aria-hidden="true" />{say('Guardar cliente','Save customer')}</Button></form>}{feedback&&!showForm&&<p role="status">{feedback}</p>}<Section title={say('Clientes','Customers')}><label className="pm-search"><span className="pm-sr-only">{say('Pesquisar clientes','Search customers')}</span><input type="search" aria-label={say('Pesquisar clientes','Search customers')} placeholder={say('Pesquisar…','Search…')} value={search} onChange={event=>setSearch(event.target.value)}/></label><div className="pm-demo-grid">{filtered.map(customer=><article className="pm-card pm-demo-record" key={customer.id}><div className="pm-section-heading"><UserRound aria-hidden/><span className="pm-status" data-tone="neutral">CRM</span></div><h2>{customer.fullName}</h2><p>{customer.email} · {customer.phone}</p><Row label="NIF" value={customer.nif}/><Row label={say('Notas','Notes')} value={customer.notes||say('Sem notas','No notes')}/></article>)}</div>{!filtered.length&&<p role="status">{say('Nenhum cliente encontrado.','No customer found.')}</p>}</Section></>;
}
